# Generated by Django 4.0.6 on 2022-07-31 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_name', models.CharField(max_length=100, verbose_name='Resturant Name')),
                ('resturant_img', models.CharField(max_length=500, verbose_name='Resturant Image URL')),
                ('address', models.CharField(max_length=100, verbose_name='Resturant Adress')),
                ('cusine_type', models.CharField(max_length=100, verbose_name='Type of Food?')),
                ('date', models.DateField(verbose_name='Date of Visit')),
                ('time', models.TimeField(verbose_name='Time of Visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1, verbose_name='Rating out of 5')),
                ('upcoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.upcoming')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu Item Name')),
                ('price', models.CharField(max_length=100, verbose_name='How Much?')),
                ('upcoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.upcoming')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('upcoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.upcoming')),
            ],
        ),
    ]
