# Generated by Django 4.0.6 on 2022-08-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_upcoming_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcoming',
            options={'ordering': ['date']},
        ),
    ]
